import streamlit as st
import pandas as pd
from PIL import Image

# --- 1. Page Configuration ---
st.set_page_config(
    page_title="UrbanFlow | Forecasting & Causality Engine",
    page_icon="🚕",
    layout="wide"
)

st.title("🚕 UrbanFlow: Marketplace Intelligence Engine")
st.markdown("""
Welcome to the UrbanFlow executive dashboard. This project demonstrates high-volume hierarchical time-series forecasting and econometric causal inference using NYC TLC data.
""")

# --- 2. Load Data ---
@st.cache_data
def load_forecast_data():
    # Load the results generated by our LightGBM model locally
    try:
        df = pd.read_csv('forecast_results.csv')
        df['ds'] = pd.to_datetime(df['ds'])
        return df
    except FileNotFoundError:
        return None

df_forecast = load_forecast_data()

# --- 3. Dashboard Tabs ---
tab1, tab2 = st.tabs(["📈 ML Forecasting Engine", "⚖️ Causal Pricing Inference"])

# --- TAB 1: Forecasting ---
with tab1:
    st.header("Hierarchical Demand Forecasting (LightGBM)")
    
    col1, col2, col3 = st.columns(3)
    col1.metric(label="Model Architecture", value="LightGBM")
    col2.metric(label="Temporal Lags Used", value="1h, 24h, 168h")
    col3.metric(label="Overall Error (WAPE)", value="18.09%", delta="-27% vs Baseline", delta_color="inverse")
    
    st.markdown("### Zone-Level Forecast vs Actuals")
    if df_forecast is not None:
        # Let the user select a specific taxi zone to inspect
        zones = df_forecast['unique_id'].unique()
        selected_zone = st.selectbox("Select Taxi Zone ID to View:", zones)
        
        # Filter and plot
        zone_data = df_forecast[df_forecast['unique_id'] == selected_zone]
        
        st.line_chart(
            data=zone_data.set_index('ds')[['y', 'LGBMRegressor']], 
            color=["#FF4B4B", "#0068C9"] # Red for Actual, Blue for Prediction
        )
        st.caption("Red: Actual Demand | Blue: LightGBM Forecast")
    else:
        st.warning("⚠️ `forecast_results.csv` not found. Make sure you ran the forecasting script locally and uploaded the CSV to GitHub!")

# --- TAB 2: Causal Inference ---
with tab2:
    st.header("Pricing Elasticity: The $2.50 Surcharge Impact")
    st.markdown("""
    **Methodology:** Difference-in-Differences (DiD)  
    **Treatment:** Manhattan (Subject to $2.50 Congestion Surcharge on Feb 2, 2019)  
    **Control:** Brooklyn (Exempt from Surcharge)
    """)
    
    st.info("💡 **Executive Summary:** The econometric regression isolated the demand shock of the price hike, proving a statistically significant drop in Manhattan trip volume relative to the baseline.")
    
    # Load and display the image we generated in Step 5
    try:
        img = Image.open('causal_impact_dashboard.png')
        st.image(img, use_container_width=True)
    except FileNotFoundError:
        st.warning("⚠️ `causal_impact_dashboard.png` not found. Make sure you ran the causal analysis script locally and uploaded the PNG to GitHub!")